# Generated by Django 5.1.6 on 2026-08-27 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Icon identifier for the frontend, e.g. 'laptop'.", max_length=50)),
                ('color', models.CharField(blank=True, help_text="Badge/progress-bar color key, e.g. 'blue'.", max_length=30)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(blank=True, help_text="2-4 letter tag used in generated asset codes, e.g. 'LT' for Laptops -> AF-LT-0005. If left blank, a tag is derived from the name on the fly (not matching any other category's tag exactly is not guaranteed in that case).", max_length=4, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional — only set when this brand is specific to one category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('specifications', models.JSONField(blank=True, help_text='Free-form spec sheet, e.g. {"processor": "...", "ram": "16GB"}.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_models', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_models', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
