# Generated by Django 5.2.17 on 2026-09-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_rename_person_to_employee'),
        ('catalog', '0002_seed_categories_from_assets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetModel',
            new_name='Model',
        ),
    ]
