# Generated by Django 5.2.17 on 2026-09-11 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_assetmodel_to_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='catalog.brand'),
        ),
        migrations.AlterField(
            model_name='model',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='catalog.category'),
        ),
    ]
