# Generated by Django 5.2.17 on 2026-09-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_asset_models_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='color_key',
            field=models.CharField(blank=True, default='blue', help_text="Card/badge color key chosen in the Brands form, e.g. 'blue'.", max_length=30),
        ),
    ]
