
from django.shortcuts import get_object_or_404
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters, status
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from accounts.permissions import StaffOrModelPermission

from .filters import AuditLogFilter
from .models import AuditLog
from .serializers import AuditLogSerializer, AuditLogWriteSerializer
from .services import create_audit_log


class AuditLogPagination(PageNumberPagination):
    """The frontend's Audit Logs page paginates client-side at 8 rows/page
    (see Asset-Management/src/components/audit-logs/log-view.tsx PAGE_SIZE)
    over the full log set it loads — so the default page size here is set
    high enough for that to fetch everything in one call, while still
    honoring an explicit ?page_size= for callers that want real
    server-side paging."""
    page_size = 8
    page_size_query_param = "page_size"
    max_page_size = 1000


def audit_log_queryset():
    return AuditLog.objects.select_related("actor").all()


class AuditLogListCreateAPIView(APIView):
    """GET  — paginated audit log list, newest first (AuditLog.Meta.ordering).
              Filter by ?action=CREATE|UPDATE|ASSIGN|RETURN|DELETE.
              Search (case-insensitive) by ?search= across title, actor
              name, actor email, and context.
    POST — create a manual audit-log entry. Staff or aduitlog.add_auditlog:
              audit records are system-generated by create_audit_log(), so
              normal users must not be able to inject entries. The
              authenticated request user automatically becomes the actor;
              the client cannot submit an `actor` field (see
              AuditLogWriteSerializer). Automatic logging never goes
              through this endpoint, so it is unaffected.

    Reading requires aduitlog.view_auditlog (or staff)."""

    permission_classes = [IsAuthenticated, StaffOrModelPermission]
    permission_model = AuditLog
    pagination_class = AuditLogPagination
    filter_backends = [DjangoFilterBackend, filters.SearchFilter]
    filterset_class = AuditLogFilter
    search_fields = ["title", "actor_name", "actor__email", "context"]

    def filter_queryset(self, queryset):
        for backend in list(self.filter_backends):
            queryset = backend().filter_queryset(self.request, queryset, self)
        return queryset

    def get(self, request):
        queryset = self.filter_queryset(audit_log_queryset())
        paginator = self.pagination_class()
        page = paginator.paginate_queryset(queryset, request, view=self)
        serializer = AuditLogSerializer(page, many=True)
        return paginator.get_paginated_response(serializer.data)

    def post(self, request):
        serializer = AuditLogWriteSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        # Explicit manual entry — always recorded, regardless of the
        # automatic-tracking toggles in Settings > Audit Logs.
        instance = create_audit_log(actor=request.user, respect_settings=False, **serializer.validated_data)
        return Response(AuditLogSerializer(instance).data, status=status.HTTP_201_CREATED)


class AuditLogDetailAPIView(APIView):
    """GET/PUT/PATCH/DELETE a single audit-log entry. PUT/PATCH only ever
    edit action/title/context — actor and timestamp are immutable once
    recorded (not part of AuditLogWriteSerializer's fields).

    GET requires aduitlog.view_auditlog; PUT/PATCH/DELETE require
    User.is_staff (the same admin flag used by /admin/ and the Settings API)
    or the matching change/delete permission, so audit history is read-only
    for normal users."""

    permission_classes = [IsAuthenticated, StaffOrModelPermission]
    permission_model = AuditLog

    def get_object(self, pk):
        return get_object_or_404(audit_log_queryset(), pk=pk)

    def get(self, request, pk):
        return Response(AuditLogSerializer(self.get_object(pk)).data)

    def put(self, request, pk):
        return self._update(request, pk, partial=False)

    def patch(self, request, pk):
        return self._update(request, pk, partial=True)

    def _update(self, request, pk, partial):
        instance = self.get_object(pk)
        serializer = AuditLogWriteSerializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)
        for field, value in serializer.validated_data.items():
            setattr(instance, field, value)
        instance.save()
        return Response(AuditLogSerializer(instance).data)

    def delete(self, request, pk):
        instance = self.get_object(pk)
        instance.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
