"use client";

import { useMemo, useState } from "react";
import { Mail, Plus, Search, X } from "lucide-react";
import { useCan } from "@/components/auth/context";
import { useAssets } from "@/components/assets/context";
import { useVendors } from "@/components/vendors/context";
import {
  CURRENCIES,
  PAYMENT_TERMS,
  VENDOR_TYPES,
  initials,
  typeMeta,
  type Vendor,
  type VendorType,
} from "@/components/vendors/data";
import { VendorDetailModal } from "@/components/vendors/detail-modal";
import { Modal } from "@/components/ui/modal";
import { useToast } from "@/components/ui/toast";
import { isValidEmail, normalizeEmail, normalizeIndianPhone } from "@/lib/contact";
import { cn } from "@/lib/utils";

const labelClass = "mb-1.5 block text-sm font-medium text-slate-700 dark:text-slate-300";
const inputClass =
  "w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 dark:border-slate-800 dark:bg-slate-800 dark:text-slate-100";

function OptionalTag() {
  return <span className="ml-1 text-xs font-normal text-slate-400 dark:text-slate-500">(Optional)</span>;
}

function SectionDivider({ label }: { label: string }) {
  return (
    <div className="flex items-center gap-3 pt-2">
      <span className="text-xs font-semibold uppercase tracking-wider text-slate-400 dark:text-slate-500">
        {label}
      </span>
      <div className="h-px flex-1 bg-slate-100 dark:bg-slate-800" />
    </div>
  );
}

function emptyVendorForm(vendorCode: string) {
  return {
    companyName: "",
    name: "",
    type: VENDOR_TYPES[0] as VendorType,
    contactPerson: "",
    email: "",
    phone: "",
    vendorCode,
    gstNumber: "",
    address: "",
    city: "",
    state: "",
    country: "India",
    postalCode: "",
    paymentTerms: "Net 30",
    currency: "INR",
    status: "Active" as "Active" | "Inactive",
    notes: "",
  };
}

export function VendorsGrid() {
  const { vendors, createVendor, updateVendor, deleteVendor } = useVendors();
  const { assets } = useAssets();
  const { showSuccess, showErrorFromException } = useToast();
  const canAdd = useCan("organization.add_vendor");
  const canChange = useCan("organization.change_vendor");
  const canDelete = useCan("organization.delete_vendor");
  const [query, setQuery] = useState("");
  const [typeFilter, setTypeFilter] = useState<VendorType | "All">("All");
  const [formOpen, setFormOpen] = useState(false);
  const [formMode, setFormMode] = useState<"add" | "edit">("add");
  const [editingId, setEditingId] = useState<number | null>(null);
  const [form, setForm] = useState(() => emptyVendorForm(""));
  const [formError, setFormError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [viewVendorId, setViewVendorId] = useState<number | null>(null);
  const [confirmDelete, setConfirmDelete] = useState<Vendor | null>(null);

  const stats = useMemo(() => {
    return vendors.map((v) => {
      const vendorAssets = assets.filter((a) => a.vendor === v.name);
      const totalSpend = vendorAssets.reduce((sum, a) => sum + a.cost, 0);
      const avgCost = vendorAssets.length > 0 ? totalSpend / vendorAssets.length : 0;
      return { ...v, vendorAssets, totalSpend, avgCost };
    });
  }, [vendors, assets]);

  const totalSpendAll = stats.reduce((sum, s) => sum + s.totalSpend, 0);
  const totalAssetsAll = assets.length;

  const filtered = stats.filter((v) => {
    const matchesType = typeFilter === "All" || v.type === typeFilter;
    const q = query.trim().toLowerCase();
    const matchesQuery = !q || v.name.toLowerCase().includes(q) || v.email.toLowerCase().includes(q);
    return matchesType && matchesQuery;
  });

  const viewVendor = stats.find((s) => s.id === viewVendorId) ?? null;

  function openAddModal() {
    setFormMode("add");
    setEditingId(null);
    // vendor_code is generated by the backend on create.
    setForm(emptyVendorForm(""));
    setFormError(null);
    setFormOpen(true);
  }

  function openEditModal(vendor: Vendor) {
    setFormMode("edit");
    setEditingId(vendor.id);
    setForm({
      companyName: vendor.companyName ?? "",
      name: vendor.name,
      type: vendor.type,
      contactPerson: vendor.contactPerson ?? "",
      email: vendor.email,
      phone: vendor.phone,
      vendorCode: vendor.vendorCode ?? "",
      gstNumber: vendor.gstNumber ?? "",
      address: vendor.address ?? "",
      city: vendor.city ?? "",
      state: vendor.state ?? "",
      country: vendor.country ?? "India",
      postalCode: vendor.postalCode ?? "",
      paymentTerms: vendor.paymentTerms ?? "Net 30",
      currency: vendor.currency ?? "INR",
      status: vendor.status,
      notes: vendor.notes ?? "",
    });
    setFormError(null);
    setFormOpen(true);
    setViewVendorId(null);
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    const name = form.name.trim();
    const email = form.email.trim();
    if (!name) {
      setFormError("Enter a vendor name.");
      return;
    }
    if (!email) {
      setFormError("Enter an email address.");
      return;
    }
    if (!isValidEmail(email)) {
      setFormError("Enter a valid email address.");
      return;
    }
    // Phone is optional for vendors — only checked when something was
    // typed (no fake placeholder number is ever substituted).
    const normalizedPhone = normalizeIndianPhone(form.phone);
    if (normalizedPhone === null) {
      setFormError("Enter a valid 10-digit phone number, e.g. 9876543210 (optionally with a +91 prefix).");
      return;
    }
    if (vendors.some((v) => v.name.toLowerCase() === name.toLowerCase() && v.id !== editingId)) {
      setFormError("A vendor with this name already exists.");
      return;
    }

    const input = {
      name,
      type: form.type as VendorType,
      email: normalizeEmail(email),
      phone: normalizedPhone,
      status: form.status,
      companyName: form.companyName.trim(),
      contactPerson: form.contactPerson.trim(),
      vendorCode: form.vendorCode.trim(),
      gstNumber: form.gstNumber.trim(),
      address: form.address.trim(),
      city: form.city.trim(),
      state: form.state.trim(),
      country: form.country.trim(),
      postalCode: form.postalCode.trim(),
      paymentTerms: form.paymentTerms,
      currency: form.currency,
      notes: form.notes.trim(),
    };

    setSubmitting(true);
    setFormError(null);
    try {
      if (formMode === "edit" && editingId !== null) {
        await updateVendor(editingId, input);
        showSuccess(`Vendor "${name}" updated.`);
      } else {
        await createVendor(input);
        showSuccess(`Vendor "${name}" created.`);
      }
      setFormOpen(false);
    } catch (error) {
      showErrorFromException(error);
      setFormError(error instanceof Error ? error.message : "Could not save this vendor.");
    } finally {
      setSubmitting(false);
    }
  }

  async function toggleStatus(vendor: Vendor, e: React.MouseEvent) {
    e.stopPropagation();
    try {
      // Carries every existing extended field forward — a partial payload
      // missing them would overwrite (blank out) the vendor's saved
      // company/address/procurement details, since toBackend() sends "" for
      // anything not provided.
      await updateVendor(vendor.id, {
        name: vendor.name,
        type: vendor.type,
        email: vendor.email,
        phone: vendor.phone,
        status: vendor.status === "Active" ? "Inactive" : "Active",
        companyName: vendor.companyName,
        contactPerson: vendor.contactPerson,
        vendorCode: vendor.vendorCode,
        gstNumber: vendor.gstNumber,
        address: vendor.address,
        city: vendor.city,
        state: vendor.state,
        country: vendor.country,
        postalCode: vendor.postalCode,
        paymentTerms: vendor.paymentTerms,
        currency: vendor.currency,
        notes: vendor.notes,
      });
    } catch (error) {
      showErrorFromException(error, "Could not update this vendor's status.");
    }
  }

  async function handleDelete(vendor: Vendor) {
    try {
      await deleteVendor(vendor.id);
      showSuccess(`Vendor "${vendor.name}" deleted.`);
    } catch (error) {
      showErrorFromException(error, "Could not delete this vendor.");
    } finally {
      setConfirmDelete(null);
      setViewVendorId(null);
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center animate-skew-in">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Vendor Management</h1>
          <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
            {vendors.length} vendors · {totalAssetsAll} assets · ₹{(totalSpendAll / 100000).toFixed(1)}L total spend
          </p>
        </div>
        {canAdd && (
          <button
            type="button"
            onClick={openAddModal}
            className="flex items-center gap-2 rounded-lg bg-blue-600 px-3.5 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700"
          >
            <Plus className="h-4 w-4" />
            Add Vendor
          </button>
        )}
      </div>

      <div
        className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between animate-skew-in"
        style={{ animationDelay: "120ms" }}
      >
        <div className="flex flex-wrap gap-2">
          {(["All", ...VENDOR_TYPES] as const).map((t) => {
            const count = t === "All" ? vendors.length : stats.filter((s) => s.type === t).length;
            const active = typeFilter === t;
            return (
              <button
                key={t}
                type="button"
                onClick={() => setTypeFilter(t)}
                className={cn(
                  "rounded-lg px-3 py-1.5 text-sm font-medium transition",
                  active
                    ? "bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-400"
                    : "text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800"
                )}
              >
                {t} ({count})
              </button>
            );
          })}
        </div>
        <div className="relative w-full sm:w-64">
          <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search vendors…"
            className="w-full rounded-lg border border-slate-200 bg-white py-2 pl-9 pr-3 text-sm text-slate-900 placeholder:text-slate-400 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-100"
          />
        </div>
      </div>

      <div
        className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 animate-skew-in"
        style={{ animationDelay: "240ms" }}
      >
        {filtered.map((v) => {
          const meta = typeMeta(v.type);
          const spendShare = totalSpendAll > 0 ? Math.round((v.totalSpend / totalSpendAll) * 100) : 0;
          return (
            <button
              type="button"
              key={v.id}
              onClick={() => setViewVendorId(v.id)}
              className="group flex flex-col rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm shadow-slate-900/[0.02] transition hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-md hover:shadow-slate-900/5 dark:border-slate-800 dark:bg-slate-900 dark:hover:border-slate-700"
            >
              <div className="flex items-start justify-between">
                <span
                  className={cn(
                    "flex h-11 w-11 items-center justify-center rounded-xl text-sm font-bold transition group-hover:scale-105",
                    meta.iconBg
                  )}
                >
                  {initials(v.name)}
                </span>
                <div className="flex flex-col items-end gap-1.5">
                  <span className={cn("rounded-full px-2 py-0.5 text-xs font-semibold", meta.chip)}>{v.type}</span>
                  <span
                    // Status toggle is an edit; read-only users just see the badge.
                    role={canChange ? "button" : undefined}
                    tabIndex={canChange ? 0 : undefined}
                    onClick={canChange ? (e) => toggleStatus(v, e) : undefined}
                    className={cn(
                      "flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-semibold",
                      v.status === "Active"
                        ? "bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-400"
                        : "bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400"
                    )}
                  >
                    <span className={cn("h-1.5 w-1.5 rounded-full", v.status === "Active" ? "bg-emerald-500" : "bg-slate-400")} />
                    {v.status}
                  </span>
                </div>
              </div>

              <p className="mt-4 text-base font-semibold text-slate-900 dark:text-white">{v.name}</p>
              <p className="mt-1 flex items-center gap-1 truncate text-xs text-slate-400 dark:text-slate-500">
                <Mail className="h-3 w-3 shrink-0" />
                {v.email}
              </p>

              <div className="mt-4 grid grid-cols-3 gap-2 text-center">
                <div>
                  <p className="text-sm font-bold text-slate-900 dark:text-white">{v.vendorAssets.length}</p>
                  <p className="text-[11px] text-slate-400 dark:text-slate-500">Assets</p>
                </div>
                <div>
                  <p className="text-sm font-bold text-slate-900 dark:text-white">
                    ₹{(v.totalSpend / 100000).toFixed(1)}L
                  </p>
                  <p className="text-[11px] text-slate-400 dark:text-slate-500">Spend</p>
                </div>
                <div>
                  <p className="text-sm font-bold text-slate-900 dark:text-white">
                    ₹{v.avgCost >= 1000 ? `${(v.avgCost / 1000).toFixed(1)}K` : v.avgCost.toFixed(0)}
                  </p>
                  <p className="text-[11px] text-slate-400 dark:text-slate-500">Avg Cost</p>
                </div>
              </div>

              <div className="mt-4 h-2 w-full overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800">
                <div
                  className={cn("h-full rounded-full bg-gradient-to-r", meta.bar)}
                  style={{ width: `${spendShare}%` }}
                />
              </div>
              <p className="mt-2 text-right text-xs text-slate-400 dark:text-slate-500">{spendShare}% of total spend</p>
            </button>
          );
        })}

        {filtered.length === 0 && (
          <div className="col-span-full flex flex-col items-center gap-2 rounded-2xl border border-dashed border-slate-200 py-16 text-slate-400 dark:border-slate-800 dark:text-slate-500">
            <Search className="h-8 w-8" />
            <p className="text-sm">No vendors match your filters.</p>
          </div>
        )}
      </div>

      {formOpen && (
        <Modal onClose={() => setFormOpen(false)} maxWidthClassName="max-w-2xl" variant="content">
            <div className="flex shrink-0 items-center justify-between border-b border-slate-100 p-6 dark:border-slate-800">
              <h2 className="text-lg font-semibold text-slate-900 dark:text-white">
                {formMode === "edit" ? "Edit Vendor" : "Add Vendor"}
              </h2>
              <button
                type="button"
                onClick={() => setFormOpen(false)}
                className="flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto p-6">
              <div className="space-y-4">
                <SectionDivider label="Basic Information" />

                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <div>
                    <label className={labelClass}>
                      Company Name
                      <OptionalTag />
                    </label>
                    <input
                      type="text"
                      value={form.companyName}
                      onChange={(e) => setForm((f) => ({ ...f, companyName: e.target.value }))}
                      placeholder="e.g. Rashi Peripherals Pvt. Ltd."
                      className={inputClass}
                    />
                  </div>
                  <div>
                    <label className={labelClass}>
                      Vendor Name <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="text"
                      value={form.name}
                      onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))}
                      placeholder="e.g. Rashi Peripherals"
                      className={inputClass}
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <div>
                    <label className={labelClass}>
                      Vendor Type <span className="text-red-500">*</span>
                    </label>
                    <select
                      value={form.type}
                      onChange={(e) => setForm((f) => ({ ...f, type: e.target.value as VendorType }))}
                      className={inputClass}
                    >
                      {VENDOR_TYPES.map((t) => (
                        <option key={t} value={t}>
                          {t}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className={labelClass}>
                      Contact Person
                      <OptionalTag />
                    </label>
                    <input
                      type="text"
                      value={form.contactPerson}
                      onChange={(e) => setForm((f) => ({ ...f, contactPerson: e.target.value }))}
                      placeholder="e.g. Priya Sharma"
                      className={inputClass}
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <div>
                    <label className={labelClass}>
                      Email <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="email"
                      value={form.email}
                      onChange={(e) => setForm((f) => ({ ...f, email: e.target.value }))}
                      placeholder="sales@vendor.com"
                      className={inputClass}
                    />
                  </div>
                  <div>
                    <label className={labelClass}>
                      Phone
                      <OptionalTag />
                    </label>
                    <input
                      type="text"
                      value={form.phone}
                      onChange={(e) => setForm((f) => ({ ...f, phone: e.target.value }))}
                      placeholder="+91 90000 00000"
                      className={inputClass}
                    />
                  </div>
                </div>

                <SectionDivider label="Business Information" />

                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <div>
                    <label className={labelClass}>
                      Vendor Code
                    </label>
                    <input
                      type="text"
                      value={form.vendorCode}
                      readOnly
                      placeholder="Generated on save"
                      title="Generated by the system"
                      className={cn(inputClass, "font-mono")}
                    />
                  </div>
                  <div>
                    <label className={labelClass}>
                      GST / Tax ID
                      <OptionalTag />
                    </label>
                    <input
                      type="text"
                      value={form.gstNumber}
                      onChange={(e) => setForm((f) => ({ ...f, gstNumber: e.target.value }))}
                      placeholder="e.g. 27AAAPL1234C1Z5"
                      className={inputClass}
                    />
                  </div>
                </div>

                <SectionDivider label="Address" />

                <div>
                  <label className={labelClass}>
                    Address
                    <OptionalTag />
                  </label>
                  <input
                    type="text"
                    value={form.address}
                    onChange={(e) => setForm((f) => ({ ...f, address: e.target.value }))}
                    placeholder="Street, building, area"
                    className={inputClass}
                  />
                </div>

                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <div>
                    <label className={labelClass}>
                      City
                      <OptionalTag />
                    </label>
                    <input
                      type="text"
                      value={form.city}
                      onChange={(e) => setForm((f) => ({ ...f, city: e.target.value }))}
                      className={inputClass}
                    />
                  </div>
                  <div>
                    <label className={labelClass}>
                      State
                      <OptionalTag />
                    </label>
                    <input
                      type="text"
                      value={form.state}
                      onChange={(e) => setForm((f) => ({ ...f, state: e.target.value }))}
                      className={inputClass}
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <div>
                    <label className={labelClass}>
                      Country
                      <OptionalTag />
                    </label>
                    <input
                      type="text"
                      value={form.country}
                      onChange={(e) => setForm((f) => ({ ...f, country: e.target.value }))}
                      className={inputClass}
                    />
                  </div>
                  <div>
                    <label className={labelClass}>
                      Postal Code
                      <OptionalTag />
                    </label>
                    <input
                      type="text"
                      value={form.postalCode}
                      onChange={(e) => setForm((f) => ({ ...f, postalCode: e.target.value }))}
                      className={inputClass}
                    />
                  </div>
                </div>

                <SectionDivider label="Procurement" />

                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <div>
                    <label className={labelClass}>Payment Terms</label>
                    <select
                      value={form.paymentTerms}
                      onChange={(e) => setForm((f) => ({ ...f, paymentTerms: e.target.value }))}
                      className={inputClass}
                    >
                      {PAYMENT_TERMS.map((term) => (
                        <option key={term} value={term}>
                          {term}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className={labelClass}>Currency</label>
                    <select
                      value={form.currency}
                      onChange={(e) => setForm((f) => ({ ...f, currency: e.target.value }))}
                      className={inputClass}
                    >
                      {CURRENCIES.map((c) => (
                        <option key={c.code} value={c.code}>
                          {c.label}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>

                <SectionDivider label="Status" />

                <div>
                  <label className={labelClass}>
                    Status <span className="text-red-500">*</span>
                  </label>
                  <select
                    value={form.status}
                    onChange={(e) => setForm((f) => ({ ...f, status: e.target.value as "Active" | "Inactive" }))}
                    className={cn(inputClass, "sm:w-56")}
                  >
                    <option value="Active">Active</option>
                    <option value="Inactive">Inactive</option>
                  </select>
                </div>

                <div>
                  <label className={labelClass}>
                    Notes
                    <OptionalTag />
                  </label>
                  <textarea
                    value={form.notes}
                    onChange={(e) => setForm((f) => ({ ...f, notes: e.target.value }))}
                    rows={2}
                    placeholder="Internal notes about this vendor..."
                    className={cn(inputClass, "resize-none")}
                  />
                </div>

                {formError && (
                  <p className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-600 dark:bg-red-500/10 dark:text-red-400">
                    {formError}
                  </p>
                )}
              </div>

              <div className="mt-5 flex justify-end gap-2 border-t border-slate-100 pt-4 dark:border-slate-800">
                <button
                  type="button"
                  onClick={() => setFormOpen(false)}
                  className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 transition hover:bg-slate-50 dark:border-slate-800 dark:text-slate-300 dark:hover:bg-slate-800"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={submitting}
                  className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-70"
                >
                  {submitting ? "Saving…" : formMode === "edit" ? "Save Changes" : "Add Vendor"}
                </button>
              </div>
            </form>
        </Modal>
      )}

      {viewVendor && (
        <VendorDetailModal
          vendor={viewVendor}
          assets={viewVendor.vendorAssets}
          onClose={() => setViewVendorId(null)}
          onEdit={canChange ? openEditModal : undefined}
          onDelete={canDelete ? setConfirmDelete : undefined}
        />
      )}

      {confirmDelete && (
        <Modal onClose={() => setConfirmDelete(null)} maxWidthClassName="max-w-sm" zIndexClassName="z-40">
            <h2 className="text-lg font-semibold text-slate-900 dark:text-white">Delete vendor?</h2>
            <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">
              This will permanently delete &quot;{confirmDelete.name}&quot;. This can&apos;t be undone.
            </p>
            <div className="mt-5 flex justify-end gap-2">
              <button
                type="button"
                onClick={() => setConfirmDelete(null)}
                className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 transition hover:bg-slate-50 dark:border-slate-800 dark:text-slate-300 dark:hover:bg-slate-800"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={() => handleDelete(confirmDelete)}
                className="rounded-lg bg-red-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-red-700"
              >
                Delete
              </button>
            </div>
        </Modal>
      )}
    </div>
  );
}
