# Generated by Django 5.2.17 on 2026-09-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Password reset')], max_length=20),
        ),
    ]
