from django.contrib import admin

from .models import Notification


@admin.register(Notification)
class NotificationAdmin(admin.ModelAdmin):
    list_display = ("title", "type", "recipient", "is_read", "created_at")
    list_filter = ("type", "is_read", "priority")
    search_fields = ("title", "message", "recipient__username")
    raw_id_fields = ("recipient",)
    # Rows are generated by notifications.services; admin is for inspection.
    readonly_fields = ("dedupe_key", "created_at", "read_at")
