"""
Django settings for asset_backend project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, etc.)
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Every developer/environment must set their own DJANGO_SECRET_KEY in .env
# (generate one with: python -c "import secrets; print(secrets.token_urlsafe(50))").
# We deliberately do NOT fall back to a randomly generated key here — a key that
# changes on every restart silently invalidates all existing sessions/JWTs.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is not set. Add it to your .env file — generate one with:\n"
        '  python -c "import secrets; print(secrets.token_urlsafe(50))"\n'
        "Each developer must generate and keep their own; never share or commit this value."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() in {"1", "true", "yes"}

ALLOWED_HOSTS = [host for host in os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if host]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'accounts',
    'aduitlog',
    'assets',
    'catalog',
    'dashboard',
    'operation',
    'operations',
    'organization',
    'reports',
    'system_settings',
    'notifications',
    'django_extensions',
]

# Stock ModelBackend authentication; permission lookup skips roles (Groups)
# switched off in Roles & Permissions — see accounts/backends.py.
AUTHENTICATION_BACKENDS = ['accounts.backends.RoleAwareModelBackend']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Settings > System > Maintenance Mode — 503 for non-staff API calls.
    # Last, so CorsMiddleware still adds CORS headers to its responses.
    'system_settings.middleware.MaintenanceModeMiddleware',
]

ROOT_URLCONF = 'asset_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'asset_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Replaces Django's MinimumLengthValidator: minimum length and the
        # uppercase/lowercase/number/special rules come from Settings >
        # Security (system_settings.SystemSettings) at validation time.
        'NAME': 'system_settings.validators.SettingsPasswordPolicyValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # accounts/views.py sets throttle_scope='accounts_login' etc. on 6 views,
    # but with no DEFAULT_THROTTLE_RATES and no throttle_classes anywhere,
    # DRF's ScopedRateThrottle never actually ran — those scopes were inert,
    # so login/register/OTP requests had zero rate limiting. Rates below
    # activate them (only for the views that opt in via throttle_classes in
    # accounts/views.py — no other endpoint in the project is affected).
    'DEFAULT_THROTTLE_RATES': {
        'accounts_login': '10/min',
        'accounts_register': '5/min',
        'accounts_forgot_password': '5/min',
        'accounts_resend_otp': '5/min',
        'accounts_verify_otp': '10/min',
        'accounts_reset_password': '10/min',
        # accounts.views.ChangePasswordAPIView — guards current-password guessing.
        'accounts_change_password': '5/min',
        # system_settings.views.TestEmailAPIView — every call sends a real email.
        'settings_test_email': '5/min',
    },
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

CORS_ALLOWED_ORIGINS = [
    # Local frontend
    'http://127.0.0.1:3000',
    'http://localhost:3000',

    # Local backend (only needed if browser requests originate here)
    'http://localhost:8000',
    'http://127.0.0.1:8000',

    # LAN frontend/backend access
    'http://192.168.0.168:3000',

    # LocalTunnel URLs
    'https://bitter-cloths-hug.loca.lt',
    'https://yellow-shrimps-exist.loca.lt',
]

# Every API call carries `Authorization: Bearer` (and JSON bodies set
# Content-Type: application/json), neither of which is CORS-safelisted, so
# the browser preflights each cross-origin request with OPTIONS — expected,
# not a misconfiguration. This lets the browser reuse a preflight result
# per URL for up to a day (browsers cap it lower: Chromium at 2 hours).
# Stated explicitly; it is also django-cors-headers' default.
CORS_PREFLIGHT_MAX_AGE = 86400

# Baseline hosts for the current LAN/tunnel setup, extended (never replaced)
# with whatever DJANGO_ALLOWED_HOSTS lists in .env — previously this literal
# assignment silently overwrote the env-driven ALLOWED_HOSTS computed above
# (line ~45), so adding a host to .env had zero effect. Merging preserves
# every host that already worked while restoring env-based configurability.
_DEFAULT_ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '192.168.0.168',

    # LocalTunnel host
    'orange-queens-post.loca.lt',
    'gold-ends-kneel.loca.lt',
    'nice-bees-go.loca.lt',
    'assetflow-api-live.loca.lt',
]
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS + _DEFAULT_ALLOWED_HOSTS))

# Gmail SMTP configuration. Every value that can hold a secret or an
# account-specific address comes from .env ONLY — nothing is hardcoded here.
#
# .strip() on the raw env values guards against the #1 real-world cause of
# "Username and Password not accepted" SMTP errors: a trailing newline or
# stray space picked up when the App Password was copied into .env (Gmail
# displays it as "xxxx xxxx xxxx xxxx" but the actual credential has no
# spaces — copying the displayed form verbatim, or leaving a trailing
# newline from the editor, produces exactly this failure).
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = (os.getenv("EMAIL_HOST_USER") or "").strip()
EMAIL_HOST_PASSWORD = (os.getenv("EMAIL_HOST_PASSWORD") or "").replace(" ", "").strip()
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

_missing_email_settings = [
    name for name, value in (
        ("EMAIL_HOST_USER", EMAIL_HOST_USER),
        ("EMAIL_HOST_PASSWORD", EMAIL_HOST_PASSWORD),
    ) if not value
]
if _missing_email_settings:
    raise ImproperlyConfigured(
        "Missing required email setting(s) in .env: "
        + ", ".join(_missing_email_settings)
        + ". Forgot-password OTP delivery requires a Gmail address in "
        "EMAIL_HOST_USER and a 16-character Gmail App Password (not your "
        "normal account password) in EMAIL_HOST_PASSWORD — generate one at "
        "https://myaccount.google.com/apppasswords (requires 2-Step "
        "Verification to be enabled on that Google account)."
    )
if EMAIL_PORT != 587 or not EMAIL_USE_TLS:
    raise ImproperlyConfigured(
        "EMAIL_PORT/EMAIL_USE_TLS were changed from the required Gmail STARTTLS "
        "values (port 587, TLS enabled)."
    )
