# Generated by Django 5.2.17 on 2026-09-08 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('ASSIGN', 'Assign'), ('RETURN', 'Return'), ('DELETE', 'Delete')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('actor_name', models.CharField(blank=True, default='', help_text="Snapshot of the actor's display name at the time of the event.", max_length=150)),
                ('context', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='auditlog_timestamp_idx'), models.Index(fields=['action', '-timestamp'], name='auditlog_action_idx'), models.Index(fields=['actor', '-timestamp'], name='auditlog_actor_idx')],
            },
        ),
    ]
