# Generated by Django 5.2.17 on 2026-09-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduitlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('ASSIGN', 'Assign'), ('RETURN', 'Return'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=10),
        ),
    ]
