# Generated by Django 5.2.17 on 2026-08-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_move_catalog_to_catalog_app'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='organization.vendor'),
        ),
        migrations.AddField(
            model_name='department',
            name='color_key',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='department',
            name='icon_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('headquarters', 'Headquarters'), ('branch_office', 'Branch Office'), ('remote', 'Remote')], default='branch_office', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='employee_id',
            field=models.CharField(blank=True, help_text="Server-generated, e.g. 'EMP-1001' — see organization.codes.next_employee_id.", max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='assets.location'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
