# Generated by Django 5.1.6 on 2026-08-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_department_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('headquarters', 'Headquarters'), ('branch_office', 'Branch Office'), ('remote', 'Remote')], default='headquarters', max_length=20),
        ),
    ]
