# Generated by Django 5.2.17 on 2026-09-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_rename_person_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_provider',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
