# Generated by Django 5.2.17 on 2026-09-03 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0010_location_created_at_location_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('vendor', models.CharField(blank=True, default='', max_length=150)),
                ('category', models.CharField(choices=[('Productivity', 'Productivity'), ('Security', 'Security'), ('Design', 'Design'), ('Development', 'Development'), ('Communication', 'Communication'), ('Cloud Storage', 'Cloud Storage'), ('Operating System', 'Operating System'), ('Other', 'Other')], default='Other', max_length=30)),
                ('license_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Annual', 'Annual'), ('Perpetual', 'Perpetual'), ('One-Time', 'One-Time')], max_length=15)),
                ('license_key', models.CharField(blank=True, default='', max_length=100)),
                ('total_seats', models.PositiveIntegerField(default=1)),
                ('seats_used', models.PositiveIntegerField(default=0)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('total_qty', models.PositiveIntegerField(default=0)),
                ('assigned_qty', models.PositiveIntegerField(default=0)),
                ('reorder_threshold', models.PositiveIntegerField(default=0)),
                ('reorder_qty', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vendor', models.CharField(blank=True, default='', max_length=150)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_order', models.CharField(blank=True, default='', max_length=50)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, default='', max_length=100)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Good', max_length=10)),
                ('item_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Discontinued', 'Discontinued')], default='Active', max_length=15)),
                ('last_restocked', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='assets.location')),
            ],
            options={
                'verbose_name_plural': 'accessories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Preventive', 'Preventive'), ('Corrective', 'Corrective'), ('Inspection', 'Inspection'), ('Battery Replace', 'Battery Replace'), ('OS Reinstall', 'OS Reinstall'), ('Software Update', 'Software Update')], max_length=20)),
                ('technician', models.CharField(max_length=150)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=15)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='assets.asset')),
            ],
            options={
                'ordering': ['-scheduled_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('issue_type', models.CharField(choices=[('Screen Damage', 'Screen Damage'), ('Battery Issue', 'Battery Issue'), ('Keyboard / Input', 'Keyboard / Input'), ('Charging / Power', 'Charging / Power'), ('Motherboard', 'Motherboard'), ('Software / OS', 'Software / OS'), ('Water / Liquid Damage', 'Water / Liquid Damage'), ('Other Hardware', 'Other Hardware')], max_length=30)),
                ('issue', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=150)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('under_warranty', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reported_date', models.DateField()),
                ('expected_return_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Reported', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_records', to='assets.asset')),
            ],
            options={
                'ordering': ['-reported_date', '-id'],
            },
        ),
    ]
