# Generated by Django 5.1.6 on 2026-09-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_rename_person_to_employee'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('assigned_date', models.DateField()),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('Returned', 'Returned')], default='Assigned', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='operation.accessory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessory_assignments', to='assets.employee')),
            ],
            options={
                'ordering': ['-assigned_date', '-id'],
            },
        ),
    ]
