# Generated by Django 5.2.17 on 2026-09-25 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('assignment_created', 'Assignment created'), ('return_processed', 'Return processed'), ('repair_status_changed', 'Repair status changed'), ('maintenance_status_changed', 'Maintenance status changed'), ('purchase_order_status_changed', 'Purchase order status changed'), ('warranty_expiring', 'Warranty expiring'), ('warranty_expired', 'Warranty expired'), ('maintenance_overdue', 'Maintenance overdue'), ('repair_overdue', 'Repair overdue'), ('license_expiring', 'License expiring'), ('license_expired', 'License expired')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('target_type', models.CharField(blank=True, default='', max_length=40)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, default='', max_length=200)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notification_inbox_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'dedupe_key'), name='notification_recipient_dedupe_uniq')],
            },
        ),
    ]
