# Generated by Django 5.2.17 on 2026-09-08 07:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_person_fk_retarget_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True),
        ),
    ]
