# Generated by Django 5.2.17 on 2026-09-24 10:43

from django.db import migrations, models


def backfill_return_numbers(apps, schema_editor):
    """Number existing returns RET-001, RET-002, ... in creation order."""
    Return = apps.get_model("operations", "Return")
    for seq, ret in enumerate(Return.objects.filter(return_number__isnull=True).order_by("id"), start=1):
        ret.return_number = f"RET-{seq:03d}"
        ret.save(update_fields=["return_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_purchaseorder_gst_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='return_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(backfill_return_numbers, migrations.RunPython.noop),
    ]
